# Inital example of Staph AMR representation

# Normally the species or group
label = "1280"

# List of antimicrobials in the library
antimicrobials = [{name = "Amikacin", type = "Aminoglycosides", key = "AMI"},
                  {name = "Gentamicin", type = "Aminoglycosides", key = "GEN"},
                  {name = "Penicillin", type = "Beta-lactams", key = "PEN"},
                  {name = "Clindamycin", type = "Lincosamides", key = "CLI"},
                  {name = "Erythromycin", type = "Macrolides", key = "ERY"},
                  {name = "Ciprofloxacin", type = "Fluoroquinolones" , key = "CIP"}]

[paar]

[[paar.sets]]
name = "blaZ"
phenotypes = [{effect = "Resistance", profile = ["PEN"], modifiers = []}]
members = ["blaZ"]

[[paar.sets]]
name = "ermA_ERY"
phenotypes = [{effect = "Resistance", profile = ["ERY"], modifiers = []}]
members = ["ermA"]

[[paar.sets]]
name = "ermA_CLI"
phenotypes = [{effect = "Resistance", profile = ["CLI"], modifiers = []}]
members = ["ermA", "ermA_SDS"]

[[paar.sets]]
name = "ermC_CLI"
phenotypes = [{effect = "Resistance", profile = ["CLI"], modifiers = [{ name = "ermC_LP", effect = "INDUCED"}]}]
members = ["ermC"]

[[paar.genes]]
name = "blaZ"
pid = 80.0
coverage = 80.0
type = "Protein"
sequence = "?"

[[paar.genes]]
name = "ermA"
pid = 80.0
coverage = 80.0
type = "Protein"
sequence = "?"

[[paar.genes]]
name = "ermA_SDS"
pid = 80.0
coverage = 95.0
type = "Protein"
sequence = "?"

[[paar.genes]]
name = "ermC"
pid = 80.0
coverage = 80.0
type = "Protein"
sequence = "?"

[[paar.genes]]
name = "ermC_LP"
pid = 90.0
coverage = 95.0
type = "Protein"
sequence = "?"

[snpar]

[[snpar.sets]]
name = "grlA_S80F"
phenotypes = [{effect = "Resistance", profile = ["CIP"], modifiers = []}]
members = [ {gene="grlA", variants=["S80F"]}]

[[snpar.sets]]
name = "grlA_S80Y"
phenotypes = [{effect = "Resistance", profile = ["CIP"], modifiers = []}]
members = [ {gene="grlA", variants=["S80Y"]}]

[[snpar.sets]]
name = "grlA_E84K"
phenotypes = [{effect = "Resistance", profile = ["CIP"], modifiers = []}]
members = [ {gene="grlA", variants=["E84K"]}]

[[snpar.sets]]
name = "grlA_A116V"
phenotypes = [{effect = "Resistance", profile = ["CIP"], modifiers = []}]
members = [ {gene="grlA", variants=["A116V"]}]

[[snpar.sets]]
name = "grlA_A116E"
phenotypes = [{effect = "Resistance", profile = ["CIP"], modifiers = []}]
members = [ {gene="grlA", variants=["A116E"]}]

[[snpar.genes]]
name = "grlA"
pid = 80.0
coverage = 80.0
type = "Protein"
variants = [ "S80F", "S80Y", "E84K", "A116V", "A116E" ]
sequence = "?"