# Inital template for AMR representation

# Normally the species or group
label = "1280"

# List of antimicrobials in the library
[[antimicrobials]]
name = "Amikacin"
type = "Aminoglycosides"
key = "AMI"

[[antimicrobials]]
name = "Gentamicin"
type = "Aminoglycosides"
key = "GEN"

[[antimicrobials]]
name = "Penicillin"
type = "Beta-lactams"
key = "PEN"

[[antimicrobials]]
name = "Clindamycin"
type = "Lincosamides"
key = "CLI"

[[antimicrobials]]
name = "Erythromycin"
type = "Macrolides"
key = "ERY"

[paar]

[[paar.sets]]
name = "blaZ"
effect = "Resistance"
profile = ["PEN"]
members = ["blaZ"]
modifiers = {}

[[paar.sets]]
name = "ermA_ERY"
effect = "Resistance"
profile = ["ERY"]
resistance = ["ermA"]
modifiers = {}

[[paar.sets]]
name = "ermA_CLI"
effect = "Resistance"
profile = ["CLI"]
resistance = ["ermA", "ermA_SDS"]
modifiers = {}

[[paar.sets]]
name = "ermC_CLI"
effect = "Resistance"
profile = ["CLI"]
resistance = ["ermC"]
modifiers = { name = "ermC_LP", effect = "INDUCED"}

[[paar.genes]]
name = "blaZ"
pid = 80.0
coverage = 80.0
sequence = "?"

[[paar.genes]]
name = "ermA"
pid = 80.0
coverage = 80.0
sequence = "?"

[[paar.genes]]
name = "ermA_SDS"
pid = 80.0
coverage = 95.0
sequence = "?"

[[paar.genes]]
name = "ermC"
pid = 80.0
coverage = 80.0
sequence = "?"

[[paar.genes]]
name = "ermC_LP"
pid = 90.0
coverage = 95.0
sequence = "?"
